name: Update LeetCode Activity

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Debug - List Files
        run: ls -R

      - name: Fetch LeetCode Calendar
        run: python fetch_leetcode_data.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add leetcode_calendar.json
          git commit -m "Update LeetCode calendar"
          git push
